### ISSUE TITLE
TailwindCSS with CSS Variables

### ISSUE THREAD

**Issue by andrecasal** [resendlabs/react-email#729]
### Describe the Bug

I have a `tailwind.config.ts` file that uses CSS Variables:

```ts
{
	theme: {
		extend: {
			colors: {
				background: 'hsl(var(--color-background) / <alpha-value>)',
			// ...
			},
		},
	},
}
```

declared in a `tailwind.css` file:
```css
@tailwind base;
@tailwind components;
@tailwind utilities;

@layer base {
	:root {
		--color-background: 0 0% 100%; /* white */
		// ...
	}
}
```

When using the `<Tailwind config={tailwindConfig}>` component, how does one load the `tailwind.css` file too so we can use custom Tailwind classnames?

The following does not work:
```tsx
import { Container, Head, Html, Link, Tailwind, Text, Body } from '@react-email/components'
import tailwindConfig from '../../../../tailwind.config.ts'
import tailwindStylesheetUrl from '../../../styles/tailwind.css'

export function SomeEmail() {
	return (
		<Tailwind config={tailwindConfig}>
			<Html lang="en" dir="ltr">
				<Head>
					<meta charSet="utf-8" />
					<title>Welcome to André Casal!</title>
					<style type="text/css">{tailwindStylesheetUrl}</style>
				</Head>
				<Body className="bg-background">
					<Container>
						<h1>
							<Text>Welcome to André Casal!</Text>
						</h1>
					</Container>
				</Body>
			</Html>
		</Tailwind>
	)
}
```

### Link to the code that reproduces this issue

NA

### To Reproduce

NA

### Expected Behavior

NA
